from DAG import DAG
dag = DAG()
dag.add_node("a",info = {"sub":"L","infom":"222"})
dag.add_node("b")
dag.add_node("c")
dag.add_node("d")
dag.add_edge("a", "b", info = "a和b是第一条边")
dag.add_edge("a", "d")
dag.add_edge("b", "c")
# print(dag.topological_sort())
# print(dag.graph)
# print(dag.all_downstreams("b"))
# print(dag.node_info)
# print(dag.edge_info)
graphs = []
graphs.append(dag)

dag = DAG()
dag.add_node("a",info = {"sub":"L","infom":"666"})
dag.add_node("b")
dag.add_node("c")
dag.add_node("d",info = 'd1 是d节点')
dag.add_edge("a", "d", info = "a和d是第一条边")
dag.add_edge("a", "d")
dag.add_edge("b", "c")
# print(dag.topological_sort())
# print(dag.graph)
# print(dag.all_downstreams("b"))
# print(dag.node_info)
# print(dag.edge_info)
graphs.append(dag)
# print("--------------")
# print(graphs[1].node_info)